set -g default-terminal "xterm-256color"
set -g aggressive-resize on

set -g window-status-format " #W "
set -g window-status-style bg=black,fg=white
set -g window-status-current-format " #W "
set -g window-status-current-style bg=brightblack,fg=cyan
set -g window-status-separator ""

set -g status-left ""
set -g status-right " tmux: #(whoami)@#H"
set -g status-style bg=black,fg=white
set -g status-position bottom
set -g status-interval 1

set -g pane-border-style fg=white
set -g pane-active-border-style fg=cyan

set -g set-titles on
set -g set-titles-string "#T"

set -g message-style bg=black,fg=white
set -g mode-style bg=white,fg=black

unbind %

set -g prefix C-a
bind a send-prefix

bind | split-window -h
bind - split-window -v

set -g mouse
set -g xterm-keys on

new-session -s main
